replicaCount: 1

image:
  repository: hemantkb66/go-web-app
  pullPolicy: IfNotPresent
  tag: "16239718880"

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
